(function(){
  "use strict";
  var STATES=["WAVE_1_ADVANCE","WAVE_2_FORMING","WAVE_2_NEAR_COMPLETION","EARLY_WAVE_3","WAVE_3_CONTINUATION","WAVE_4_CORRECTION","WAVE_5_ADVANCE"];
  var COLORS={WAVE_1_ADVANCE:"#a78bfa",WAVE_2_FORMING:"#60a5fa",WAVE_2_NEAR_COMPLETION:"#38bdf8",EARLY_WAVE_3:"#2dd4bf",WAVE_3_CONTINUATION:"#22c55e",WAVE_4_CORRECTION:"#f59e0b",WAVE_5_ADVANCE:"#f472b6",UNKNOWN:"#94a3b8",WAVE_3_EXTENDED:"#fb7185"};
  var $=function(s){return document.querySelector(s);},items=[],selected=null,loadToken=0;
  var dom={loading:$("#loading"),error:$("#error"),errorMessage:$("#error-message"),empty:$("#empty"),workspace:$("#workspace"),search:$("#search"),wave:$("#wave-filter"),laneFilter:$("#lane-filter"),select:$("#symbol-select"),retry:$("#retry"),errorRetry:$("#error-retry"),provenance:$("#provenance"),symbol:$("#symbol"),lane:$("#lane"),blocked:$("#blocked"),chart:$("#chart"),chartEmpty:$("#chart-empty"),chartStatus:$("#chart-status"),legend:$("#legend"),summary:$("#summary"),supporting:$("#supporting"),contradicting:$("#contradicting"),missing:$("#missing"),transitions:$("#transitions")};
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c];});}
  function contextOf(item){var c=item&&item.wave&&item.wave.context;return c&&typeof c==="object"&&!Array.isArray(c)?c:{};}
  function mappedState(item){var s=contextOf(item).mapped_state;return STATES.indexOf(s)>=0?s:"UNKNOWN";}
  function actionability(item){var state=mappedState(item),lane=item&&item.decision_lane||"DATA_BLOCKED";if(["WAVE_2_FORMING","WAVE_2_NEAR_COMPLETION","WAVE_4_CORRECTION","UNKNOWN"].indexOf(state)>=0)return "Non-actionable context · backend lane "+lane;return lane==="REVIEW_NOW"?"Review eligible only because backend lane is REVIEW_NOW":"Not review eligible · backend lane "+lane;}
  function markerRows(item){var wave=item&&item.wave||{},raw=Array.isArray(wave.evidence_markers)?wave.evidence_markers:Array.isArray(wave.markers)?wave.markers:[];return raw.filter(function(m){return m&&m.timeframe==="daily"&&m.timestamp!=null&&m.price!=null&&Number.isFinite(Number(m.price));});}
  function validatePage(data,page){if(!data||!Array.isArray(data.items)||data.universe_filter!=="marginable_long")throw new Error("canonical universe contract mismatch");if(data.page!==page||!Number.isInteger(data.total_pages)||!Number.isInteger(data.total_items)||data.returned_count!==data.items.length)throw new Error("canonical pagination contract mismatch");return data;}
  async function fetchAllCandidates(signal){var page=1,all=[],first=null,totalPages=1;do{var url="/api/setup-candidates?universe=marginable_long&page="+page+"&page_size=100";var res=await fetch(url,{signal:signal});if(!res.ok)throw new Error("setup candidates HTTP "+res.status);var data=validatePage(await res.json(),page);if(!first)first=data;totalPages=data.total_pages;all=all.concat(data.items);page+=1;}while(page<=totalPages);if(first&&all.length!==first.total_items)throw new Error("incomplete full-universe pagination");return{items:all,meta:first};}
  function showOnly(name){dom.loading.hidden=name!=="loading";dom.error.hidden=name!=="error";dom.empty.hidden=name!=="empty";dom.workspace.hidden=name!=="workspace";}
  function list(value){return Array.isArray(value)&&value.length?value:["Unavailable"]}
  function renderList(node,value){node.innerHTML=list(value).map(function(x){return"<li>"+esc(typeof x==="object"?JSON.stringify(x):x)+"</li>";}).join("");}
  function filtered(){var q=dom.search.value.trim().toUpperCase(),w=dom.wave.value,l=dom.laneFilter.value;return items.filter(function(item){return(!q||(String(item.symbol||"")+" "+String(item.name||"")).toUpperCase().indexOf(q)>=0)&&(w==="ALL"||mappedState(item)===w)&&(l==="ALL"||item.decision_lane===l);});}
  function applyFilters(){var visible=filtered();dom.select.innerHTML=visible.map(function(i){return'<option value="'+esc(i.symbol)+'">'+esc(i.symbol+" · "+mappedState(i)+" · "+(i.decision_lane||"DATA_BLOCKED"))+'</option>';}).join("");if(!visible.length){selected=null;showOnly("empty");return;}showOnly("workspace");var keep=visible.some(function(i){return selected&&i.symbol===selected.symbol;});selectItem(keep?selected:visible[0]);}
  function evidenceMarkerKind(marker){return marker.context_state||marker.mapped_state||marker.wave_state||marker.kind||"UNKNOWN";}
  function renderEvidence(item){var c=contextOf(item),secondary=Array.isArray(c.secondary_markers)&&c.secondary_markers.indexOf("WAVE_3_EXTENDED")>=0?["WAVE_3_EXTENDED"]:[];dom.symbol.textContent=item.symbol||"—";dom.lane.textContent=item.decision_lane||"DATA_BLOCKED";var rows=[["Mapped context",mappedState(item)],["Secondary",secondary.length?secondary.join(", "):"None"],["Confidence",c.confidence||"NOT_VERIFIED"],["Rule",c.rule_version||"Unavailable"],["Daily source",c.source_timeframe==="daily"?"daily":"Unavailable"],["First / last",c.first_context_date&&c.last_context_date?c.first_context_date+" / "+c.last_context_date:"Unavailable"],["Actionability",actionability(item)],["Rationale",c.rationale||"Unavailable"]];dom.summary.innerHTML=rows.map(function(r){return"<dt>"+esc(r[0])+"</dt><dd>"+esc(r[1])+"</dd>";}).join("");renderList(dom.supporting,c.supporting_evidence);renderList(dom.contradicting,c.contradicting_evidence);renderList(dom.missing,c.missing_evidence);renderList(dom.transitions,c.transitions&&c.transitions.length?c.transitions:["Unavailable · canonical API has no source-linked transition history"]);var status=item.data_status||{};var blocked=item.decision_lane==="DATA_BLOCKED"||status.sufficient===false||status.freshness==="stale"||status.daily_freshness==="stale";dom.blocked.hidden=!blocked;dom.blocked.textContent=blocked?"Stale / data-blocked evidence: "+(status.reason_code||list(status.reason_codes).join(", ")):"";var kinds={};markerRows(item).forEach(function(m){kinds[evidenceMarkerKind(m)]=true;});kinds[mappedState(item)]=true;secondary.forEach(function(s){kinds[s]=true;});dom.legend.innerHTML='<span><i class="dot" style="background:#dbeafe"></i>Daily close / high-low</span>'+Object.keys(kinds).map(function(k){return'<span><i class="dot" style="background:'+esc(COLORS[k]||COLORS.UNKNOWN)+'"></i>'+esc(k)+'</span>';}).join("")+(markerRows(item).length?"":'<span>Exact Daily markers unavailable</span>');}
  function dateKey(v){return String(v||"").slice(0,10);}
  function drawChart(payload,item){window.__signalixWaveChart=payload;var candles=payload&&Array.isArray(payload.candles)?payload.candles:[];dom.chartStatus.textContent="Daily · authoritative /api/chart-db · "+(payload.latest_time||candles.length+" bars");if(candles.length<2){dom.chartEmpty.hidden=false;var ctx=dom.chart.getContext("2d");ctx.clearRect(0,0,dom.chart.width,dom.chart.height);return;}dom.chartEmpty.hidden=true;var canvas=dom.chart,rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(320,Math.round(rect.width*dpr));canvas.height=Math.max(300,Math.round(rect.height*dpr));var ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);var w=canvas.width/dpr,h=canvas.height/dpr,left=50,right=18,top=18,bottom=36,plotH=h-top-bottom;var lows=candles.map(function(c){return Number(c.low!=null?c.low:c.close);}),highs=candles.map(function(c){return Number(c.high!=null?c.high:c.close);});var min=Math.min.apply(null,lows),max=Math.max.apply(null,highs),span=max-min||1;function x(i){return left+i*(w-left-right)/Math.max(1,candles.length-1)}function y(v){return top+(max-Number(v))*plotH/span}ctx.clearRect(0,0,w,h);ctx.strokeStyle="#263348";ctx.fillStyle="#9eacc2";ctx.font="11px system-ui";for(var g=0;g<=4;g++){var gy=top+g*plotH/4;ctx.beginPath();ctx.moveTo(left,gy);ctx.lineTo(w-right,gy);ctx.stroke();ctx.fillText((max-g*span/4).toFixed(2),2,gy+4)}ctx.strokeStyle="#61728e";ctx.lineWidth=1;candles.forEach(function(c,i){ctx.beginPath();ctx.moveTo(x(i),y(c.high!=null?c.high:c.close));ctx.lineTo(x(i),y(c.low!=null?c.low:c.close));ctx.stroke()});ctx.strokeStyle="#dbeafe";ctx.lineWidth=2;ctx.beginPath();candles.forEach(function(c,i){i?ctx.lineTo(x(i),y(c.close)):ctx.moveTo(x(i),y(c.close))});ctx.stroke();var index={};candles.forEach(function(c,i){index[dateKey(c.date||c.time)]=i});markerRows(item).forEach(function(m){var i=index[dateKey(m.timestamp)];if(i==null)return;var kind=evidenceMarkerKind(m),mx=x(i),my=y(m.price);ctx.fillStyle=COLORS[kind]||COLORS[mappedState(item)]||COLORS.UNKNOWN;ctx.beginPath();ctx.arc(mx,my,5,0,Math.PI*2);ctx.fill();ctx.fillText(String(m.label||kind).slice(0,22),Math.max(left,mx-25),Math.max(top+10,my-9))});}
  async function loadChart(item,token){dom.chartStatus.textContent="Daily chart loading…";dom.chartEmpty.hidden=true;try{var res=await fetch("/api/chart-db/"+encodeURIComponent(item.symbol)+"?timeframe=1D");if(!res.ok)throw new Error("Daily chart HTTP "+res.status);var payload=await res.json();if(token!==loadToken||!selected||selected.symbol!==item.symbol)return;drawChart(payload,item);}catch(err){if(token!==loadToken)return;dom.chartStatus.textContent="Daily chart transport error · "+err.message;dom.chartEmpty.hidden=false;dom.chartEmpty.textContent="Daily chart unavailable. Retry the selected stock or full page.";}}
  async function selectItem(item){selected=item;dom.select.value=item.symbol;renderEvidence(item);var token=++loadToken;try{var res=await fetch("/api/symbol/"+encodeURIComponent(item.symbol));if(!res.ok)throw new Error("symbol detail HTTP "+res.status);var detail=await res.json();if(token!==loadToken||!selected||selected.symbol!==item.symbol)return;selected=Object.assign({},item,detail);renderEvidence(selected);loadChart(selected,token);}catch(err){if(token!==loadToken)return;dom.chartStatus.textContent="Canonical symbol detail unavailable · "+err.message;dom.chartEmpty.hidden=false;dom.chartEmpty.textContent="Wave markers and Daily chart are unavailable until canonical detail can be loaded.";}}
  async function load(){var token=++loadToken;showOnly("loading");try{var controller=new AbortController(),result=await fetchAllCandidates(controller.signal);if(token!==loadToken)return;items=result.items;var m=result.meta||{},f=m.freshness||{};dom.provenance.textContent="marginable_long · "+items.length+" / "+m.evaluated_count+" evaluated · "+(f.status||"freshness unknown")+" · "+(m.policy_version||(m.provenance||{}).policy_version||"policy unavailable");applyFilters();}catch(err){if(token!==loadToken)return;showOnly("error");dom.errorMessage.textContent=err.message;}}
  [dom.search,dom.wave,dom.laneFilter].forEach(function(n){n.addEventListener(n===dom.search?"input":"change",applyFilters)});dom.select.addEventListener("change",function(){var item=filtered().find(function(i){return i.symbol===dom.select.value});if(item)selectItem(item)});dom.retry.addEventListener("click",load);dom.errorRetry.addEventListener("click",load);window.addEventListener("resize",function(){if(selected&&window.__signalixWaveChart)drawChart(window.__signalixWaveChart,selected)});load();
})();
